### ISSUE TITLE
RTWM v2 roadmap

### ISSUE THREAD

**Issue by Corey-Maler** [Corey-Maler/RealtimeWorldMap#1]
- [ ] modern stack (typescript, webpack, etc.)
- [ ] devtools
- [ ] planet rendering subsystem
- [ ] rasterization subsystem
- [ ] high details (buildings and other static objects)
- [ ] label subsystem
- [ ] route overview
- [ ] selected object details
- [ ] area, vectors map, onmap-charts
